site_name: Slope Tools
site_url: https://slopetools.readthedocs.io/en/latest/
site_description: Documentation for the SlopeTools Python Package
site_author: Norm Jones
repo_url: https://github.com/njones61/slopetools/
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
nav:
  - Home: index.md
  - Usage Guide:
    - Input File: usage/inputfile.md
    - General Features: usage/features.md
    - Code Structure: usage/codestructure.md
  - Solution Techniques:
    - Ordinary Method of Slices: methods/oms.md
    - Bishop's Simplified Method: methods/bishop.md
    - Spencer's Method: methods/spencer.md
    - Janbu Force Equilibrium: methods/janbu.md
    - Morgenstern & Price: methods/mp.md
  - Advanced Techniques:
    - Rapid Drawdown Analysis: advanced/rapid.md
    - Reliability Analysis: advanced/reliability.md
    - Tension Crack Optimization: advanced/tcrackopt.md
  - API:
      - File I/O: api/fileio.md
      - Slice: api/slice.md
      - Solve: api/solve.md
      - Plot: api/plot.md
      - Utils: api/utils.md
  - Sample Problems:
    - Simple Slopes: samples/simple.md
    - Distributed Loads: samples/dloads.md
    - Submerged Slopes: samples/submerged.md
    - Non-Circular Surfaces: samples/non_circ.md
    - Reinforcement: samples/reinforce.md
    - Rapid Drawdown: samples/rapid.md
    - Reliability Analysis: samples/reliability.md
    - Tension Cracks: samples/tcracks.md
    - Slope Design: samples/design.md
