site_name: XSLOPE
site_url: https://xslope.readthedocs.io/en/latest/
site_description: Documentation for the xslope Python Package
site_author: Norm Jones
repo_url: https://github.com/njones61/xslope/
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
nav:
  - Home: index.md
  - Usage Guide:
    - General Features: usage/features.md
    - Code Structure: usage/structure.md
  - Limit Equilibrium Method:
    - Overview: limit_equilibrium/overview.md
    - Ordinary Method of Slices: limit_equilibrium/oms.md
    - Bishop's Simplified Method: limit_equilibrium/bishop.md
    - Janbu Method: limit_equilibrium/janbu.md
    - Force Equilibrium Methods: limit_equilibrium/force_eq.md
    - Spencer's Method: limit_equilibrium/spencer.md
    - Rapid Drawdown Analysis: limit_equilibrium/rapid.md
    - Automated Search Algorithms: limit_equilibrium/search.md
    - Reliability Analysis: limit_equilibrium/reliability.md
    - Sample Problems: limit_equilibrium/samples.md
  - Seepage Analysis:
    - Overview: seepage/overview.md
    - Problem Setup: seepage/setup.md
    - Pore pressures: seepage/pore.md
    - Sample Problems: seepage/samples.md
  - Finite Element Method:
    - Overview: finite_element/overview.md
    - Mesh Generation: finite_element/mesh.md
    - Problem Setup: finite_element/setup.md
    - Sample Problems: finite_element/samples.md
  - API:
      - File I/O: api/fileio.md
      - Slice: api/slice.md
      - Solve: api/solve.md
      - Search: api/search.md
      - Plot: api/plot.md

