site_name: XSLOPE
site_url: https://xslope.readthedocs.io/en/latest/
site_description: Documentation for the xslope Python Package
site_author: Norm Jones
repo_url: https://github.com/njones61/xslope/
copyright: Copyright &copy; 2025 Norman L. Jones. Licensed under Apache 2.0.
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_signature_annotations: false
nav:
  - Home: index.md
  - Usage Guide:
    - Installation: usage/installation.md
    - Input Template: usage/input_template.md
    - Colab Notebooks: usage/notebooks.md
    - Claude Code Skill: usage/claude/index.md
  - Limit Equilibrium Method:
    - Overview: lem/overview.md
    - Ordinary Method of Slices: lem/oms.md
    - Bishop's Simplified Method: lem/bishop.md
    - Janbu Method: lem/janbu.md
    - Force Equilibrium Methods: lem/force_eq.md
    - Spencer's Method: lem/spencer.md
    - Piles and Concrete Piers: lem/piles.md
    - Rapid Drawdown Analysis: lem/rapid.md
    - Automated Search Algorithms: lem/search.md
    - Reliability Analysis: lem/reliability.md
    - Slope Design: lem/design.md
    - Sample Problems: lem/samples.md
  - Seepage Analysis:
    - Overview: seep/overview.md
    - Seep-Slope Integration: seep/seep_slope.md
    - Sample Problems: seep/samples.md
  - Finite Element Method:
    - Overview: fem/overview.md
    - Soil Reinforcement: fem/reinforcement.md
    - Piles and Concrete Piers: fem/piles.md
    - Mesh Generation: fem/mesh.md
    - Sample Problems: fem/samples.md
  - API:
      - Advanced: api/advanced.md
      - FEM: api/fem.md
      - File I/O: api/fileio.md
      - Global Config: api/global_config.md
      - Mesh: api/mesh.md
      - Plot: api/plot.md
      - Plot FEM: api/plot_fem.md
      - Plot SEEP: api/plot_seep.md
      - SEEP: api/seep.md
      - Search: api/search.md
      - Slice: api/slice.md
      - Solve: api/solve.md
  - Coding:
      - Conda: coding/conda_guide.md
      - Contributing: coding/contributing.md

