site_name: XSLOPE
site_url: https://xslope.readthedocs.io/en/latest/
site_description: Documentation for the xslope Python Package
site_author: Norm Jones
repo_url: https://github.com/njones61/xslope/
copyright: Copyright &copy; 2025 Norman L. Jones. Licensed under Apache 2.0.
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_signature_annotations: false
nav:
  - Home: index.md
  - Usage Guide:
    - General Features: usage/features.md
    - Code Structure: usage/structure.md
  - Limit Equilibrium Method:
    - Overview: lim_eq/overview.md
    - Ordinary Method of Slices: lim_eq/oms.md
    - Bishop's Simplified Method: lim_eq/bishop.md
    - Janbu Method: lim_eq/janbu.md
    - Force Equilibrium Methods: lim_eq/force_eq.md
    - Spencer's Method: lim_eq/spencer.md
    - Rapid Drawdown Analysis: lim_eq/rapid.md
    - Automated Search Algorithms: lim_eq/search.md
    - Reliability Analysis: lim_eq/reliability.md
    - Sample Problems: lim_eq/samples.md
  - Seepage Analysis:
    - Overview: seepage/overview.md
    - Problem Setup: seepage/setup.md
    - Pore pressures: seepage/pore.md
    - Sample Problems: seepage/samples.md
  - Finite Element Method:
    - Overview: fem/overview.md
    - Mesh Generation: fem/mesh.md
    - Problem Setup: fem/setup.md
    - Sample Problems: fem/samples.md
  - API:
      - File I/O: api/fileio.md
      - Slice: api/slice.md
      - Solve: api/solve.md
      - Search: api/search.md
      - Plot: api/plot.md

