"""Generate ``latest.json`` — the update manifest attached to every release.

XSLOPE Studio's updater (Stage B) reads exactly this file and never scrapes the
release page's HTML. It is generated by CI from the artifacts that were actually
built, so the checksums always describe the bytes that were uploaded.

Usage::

    python packaging/make_latest_json.py \
        --version 0.1.58 --tag v0.1.58 \
        --repo njones61/xslope \
        --out latest.json \
        artifacts/XSLOPE-Studio-0.1.58-macos-arm64.dmg \
        artifacts/XSLOPE-Studio-0.1.58-windows-x64-setup.exe

Platform keys are ``"{sys.platform}-{platform.machine().lower()}"`` as seen by
the running app, so the updater picks its entry with a one-line lookup:

    key = f"{sys.platform}-{platform.machine().lower()}"
    entry = manifest["artifacts"][key]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone

# Filename fragment -> platform key(s) the updater will look itself up under.
# One artifact may serve several keys (a universal2 dmg serves both Macs).
PLATFORM_KEYS = [
    (re.compile(r"macos[-_]?universal", re.I), ["darwin-arm64", "darwin-x86_64"]),
    (re.compile(r"macos[-_]?arm64", re.I), ["darwin-arm64"]),
    (re.compile(r"macos[-_]?(x86_64|x64|intel)", re.I), ["darwin-x86_64"]),
    (re.compile(r"windows[-_]?(x64|amd64)", re.I), ["win32-amd64"]),
    (re.compile(r"windows[-_]?arm64", re.I), ["win32-arm64"]),
    (re.compile(r"linux[-_]?(x86_64|x64)", re.I), ["linux-x86_64"]),
]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def keys_for(filename):
    for pattern, keys in PLATFORM_KEYS:
        if pattern.search(filename):
            return keys
    return []


def build(version, tag, repo, artifacts, minimum_version="0.0.0", notes_url=None):
    base = f"https://github.com/{repo}/releases/download/{tag}"
    entry_by_key = {}
    unmatched = []
    for path in artifacts:
        name = os.path.basename(path)
        keys = keys_for(name)
        if not keys:
            unmatched.append(name)
            continue
        entry = {
            "filename": name,
            "url": f"{base}/{name}",
            "sha256": sha256(path),
            "size": os.path.getsize(path),
        }
        for key in keys:
            entry_by_key[key] = entry
    if unmatched:
        print(f"warning: no platform key matched {unmatched}", file=sys.stderr)
    return {
        "schema": 1,
        "version": version,
        "tag": tag,
        "released": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "notes_url": notes_url or f"https://github.com/{repo}/releases/tag/{tag}",
        "minimum_version": minimum_version,
        "artifacts": entry_by_key,
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--version", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--repo", default="njones61/xslope")
    ap.add_argument("--minimum-version", default="0.0.0",
                    help="oldest version that can update straight to this one")
    ap.add_argument("--notes-url", default=None)
    ap.add_argument("--out", default="latest.json")
    ap.add_argument("artifacts", nargs="+")
    args = ap.parse_args(argv)

    manifest = build(args.version, args.tag, args.repo, args.artifacts,
                     args.minimum_version, args.notes_url)
    text = json.dumps(manifest, indent=2) + "\n"
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)
    if not manifest["artifacts"]:
        raise SystemExit("latest.json has no artifacts - refusing to publish it")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
