"""Build Tutorial FEM-5's three rock-slope files (the slab, and the toppling stack).

FEM-5 teaches a rock slope whose strength is the strength of the surfaces the
rock is cut by.  Its models are built here rather than derived from the
verification corpus, and the reason is the hand check: the slab's factor of
safety is tan(phi) / tan(dip), which a reader works out with a calculator, and
no corpus row has an answer of that kind.

    docs/tutorials/files/xslope_rock_joints_start.xlsx   the section and the
                                                         rock, joints sheet empty
    docs/tutorials/files/xslope_rock_joints.xlsx         part 1: the bedding
                                                         plane and the release
                                                         joint
    docs/tutorials/files/xslope_rock_toppling.xlsx       part 2: the generated
                                                         column set on its base
                                                         plane

Nothing here hand-edits an xlsx: each file is written through the package writer
at the current template version, then re-loaded and put through the finite
element model checks, so a file that lands on disk is proved to load and to pass
them.

The section
-----------
A 12 m face cut at 60 degrees in one rock, on a 44 m section with 3 m of rock
below the toe.  The rock is declared **elastic**, which is what makes the page's
first run a test of the joints alone: a strength reduction has nothing in the
rock to divide, so it divides the joints' strength and nothing else.

Part 1 cuts one slab out of that face with two lines.  The bedding plane dips
35 degrees out of the face and daylights at the toe; the release joint stands
vertically at x = 12 and runs from the bedding plane up to the ground surface.
Both are cohesionless at phi = 40 degrees, so the slab's factor of safety is
tan 40 / tan 35 = 1.198 and neither the slab's shape nor its weight enters it.

Part 2 replaces them with a base plane at 30 degrees and a set of steeply
dipping joints generated by ``xslope.joints.parallel_set`` over a joint region,
which is the same set Studio's Build network dialog writes.  The columns the set
cuts rock into tip on the base plane rather than sliding along it.

The toppling model is the one FEM-5 ships solved, so a reader can open it and
browse a finished strength reduction without waiting for the run.  The solution
sidecars are written by ``tools/make_rock_joints_sidecars.py``, not here.

Run:  PYTHONPATH=. python3 tools/build_rock_joints.py          # all three
      PYTHONPATH=. python3 tools/build_rock_joints.py slab     # one
"""

from __future__ import annotations

import copy
import math
import os
import sys

from shapely.geometry import Polygon

from xslope import joints as xjoints
from xslope.fileio import (default_template_path, load_slope_data,
                           save_slope_data_to_xlsx)
from xslope.preflight import preflight

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "tutorials", "files")

#: A loaded model supplies the full key set a material dict and a model dict
#: carry; every field this builder cares about is set below.
BASE_WB = os.path.join(OUT, "xslope_ssrm_embankment.xlsx")

# ---- the section ------------------------------------------------------------
H = 12.0                 # height of the face
FACE_DIP = 60.0          # face angle, degrees from horizontal
CREST_X = 14.0           # crest of the face
TOE_X = CREST_X + H / math.tan(math.radians(FACE_DIP))
X1 = 26.0                # right edge of the section, 5 m past the toe: the rock is
                         # elastic and both mechanisms are behind the face, so
                         # that is all the ground the model needs
Y0 = -3.0                # bottom of the section

GAMMA = 26.0             # kN/m3
E_ROCK = 5.0e6           # kPa (5,000 MPa)
NU_ROCK = 0.25

TARGET_SIZE = 1.5        # m

# ---- part 1: the slab -------------------------------------------------------
BED_DIP = 35.0           # bedding plane, degrees out of the face
REL_X = 12.0             # the release joint, 2 m behind the crest
BED_Y_AT_REL = (TOE_X - REL_X) * math.tan(math.radians(BED_DIP))
JOINT_PHI = 40.0

# ---- part 2: the toppling stack ---------------------------------------------
BASE_DIP = 30.0          # the base plane, degrees out of the face
BASE_TIP_X = 9.0
BASE_TIP_Y = (TOE_X - BASE_TIP_X) * math.tan(math.radians(BASE_DIP))
COL_DIP = 110.0          # the column set: 110 deg is 70 deg dipping INTO the face
COL_SPACING = 1.5
COL_OFFSET = 1.25
COL_PHI = 35.0
REGION_LABEL = "Toppling zone"


def _base():
    return load_slope_data(BASE_WB)


def rock(template):
    m = copy.deepcopy(template)
    m.update(name="rock", gamma=GAMMA, gamma_sat=None, option="elastic",
             c=0.0, phi=0.0, E=E_ROCK, nu=NU_ROCK, u="none", ru=0.0,
             t_cut=None)
    for k in ("cp", "r_elev", "d", "psi", "sigma_gamma", "sigma_c", "sigma_phi",
              "sigma_cp", "sigma_d", "sigma_psi"):
        m[k] = 0.0
    return m


def section_polygon():
    return [{"polygon": Polygon([(0.0, H), (CREST_X, H), (TOE_X, 0.0),
                                 (X1, 0.0), (X1, Y0), (0.0, Y0)]),
             "mat_id": 0, "size": None}]


def joint(label, p1, p2, phi, c=0.0):
    """One joints-sheet row.  Everything but the endpoints, c and phi is blank:
    no residual branch, no dilation, no tension across the joint, and the normal
    and shear stiffnesses derived from the rock around it."""
    nan = float("nan")
    return {"label": label, "x1": p1[0], "y1": p1[1], "x2": p2[0], "y2": p2[1],
            "c": c, "phi": phi, "c_res": nan, "phi_res": nan, "dil": nan,
            "t_cut": 0.0, "kn": nan, "ks": nan, "jred": ""}


def model(joint_lines=(), joint_zones=()):
    sd = _base()
    sd["materials"] = [rock(sd["materials"][0])]
    sd["profile_lines"] = []
    sd["polygons"] = section_polygon()
    sd["joint_lines"] = list(joint_lines)
    sd["joint_zones"] = list(joint_zones)
    for key in ("reinforcement_lines", "reinforce_lines", "ssr_zones",
                "refine_zones", "non_circ", "dloads", "dloads2",
                "dload_dirs", "dload2_dirs", "pile_lines", "line_loads",
                "piezo_line", "piezo_line2"):
        sd[key] = []
    # The loader will not open a model that carries no surface, no mesh and no
    # seepage boundary, so every file here carries one starting circle, placed
    # the standard way: center above the middle of the face at twice its height,
    # tangent to the base of the section.  Nothing on FEM-5 runs it.
    sd["circles"] = [{"Xo": round((CREST_X + TOE_X) / 2.0, 2), "Yo": 2.0 * H,
                      "Depth": 0.0, "R": 2.0 * H}]
    sd["element_type"] = "tri6"
    sd["target_size"] = TARGET_SIZE
    sd["element_size_1d"] = None
    sd["unit_system"] = "si"
    sd["gamma_water"] = 9.81
    sd["max_depth"] = 0.0
    sd["water_loads"] = "manual"
    sd["mesh"] = None
    sd["k0"] = None
    sd["tension_srf"] = None
    sd["ssrm_f_min"] = None
    sd["ssrm_f_max"] = None
    return sd


def build_start():
    """The section and the rock, with nothing on the joints sheet.  The reader
    types the two lines of part 1 into it."""
    return model()


def build_slab():
    """Part 1: the bedding plane and the release joint that cut out one slab."""
    return model(joint_lines=[
        joint("bedding", (REL_X, BED_Y_AT_REL), (TOE_X, 0.0), JOINT_PHI),
        joint("release", (REL_X, BED_Y_AT_REL), (REL_X, H), JOINT_PHI),
    ])


def build_toppling():
    """Part 2: the base plane typed by hand, and the column set generated over a
    joint region, which is what Studio's Build network dialog writes."""
    region = {"polygon": [(BASE_TIP_X, BASE_TIP_Y), (TOE_X, 0.0),
                          (CREST_X, H), (BASE_TIP_X, H)],
              "label": REGION_LABEL, "size": None}
    sd = model(joint_zones=[region])
    rows = xjoints.parallel_set(sd, dip_deg=COL_DIP, spacing=COL_SPACING,
                                offset=COL_OFFSET,
                                region=f"poly:{REGION_LABEL}", label="col",
                                props={"c": 0.0, "phi": COL_PHI})
    base = joint("base plane", (BASE_TIP_X, BASE_TIP_Y), (TOE_X, 0.0), COL_PHI)
    sd["joint_lines"] = [base] + list(rows)
    return sd


#: The blocky-mass variant: the same region and base plane, filled by the
#: Voronoi generator at this block size and seed (the figure producer draws the
#: same tessellation), so the page can show what the generator's picture solves to.
VORONOI_BLOCK = 2.0
VORONOI_SEED = 7


def build_voronoi():
    """Part 2's blocky mass: the base plane typed by hand and the toppling zone
    filled by the Voronoi generator instead of the column set."""
    region = {"polygon": [(BASE_TIP_X, BASE_TIP_Y), (TOE_X, 0.0),
                          (CREST_X, H), (BASE_TIP_X, H)],
              "label": REGION_LABEL, "size": None}
    sd = model(joint_zones=[region])
    rows = xjoints.voronoi(sd, block_size=VORONOI_BLOCK, seed=VORONOI_SEED,
                           region=f"poly:{REGION_LABEL}", label="vor",
                           props={"c": 0.0, "phi": COL_PHI})
    base = joint("base plane", (BASE_TIP_X, BASE_TIP_Y), (TOE_X, 0.0), COL_PHI)
    sd["joint_lines"] = [base] + list(rows)
    return sd


BUILDS = {
    "start": ("xslope_rock_joints_start.xlsx", build_start),
    "slab": ("xslope_rock_joints.xlsx", build_slab),
    "toppling": ("xslope_rock_toppling.xlsx", build_toppling),
    "voronoi": ("xslope_rock_voronoi.xlsx", build_voronoi),
}


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    names = argv or list(BUILDS)
    print("template:", default_template_path())
    print(f"section: {H:g} m face at {FACE_DIP:g} deg, crest x = {CREST_X:g}, "
          f"toe x = {TOE_X:.4f}")
    print(f"bedding plane at {BED_DIP:g} deg meets the release joint at "
          f"({REL_X:g}, {BED_Y_AT_REL:.4f})")
    print(f"hand check: tan {JOINT_PHI:g} / tan {BED_DIP:g} = "
          f"{math.tan(math.radians(JOINT_PHI)) / math.tan(math.radians(BED_DIP)):.4f}")
    bad = 0
    for name in names:
        if name not in BUILDS:
            print(f"unknown model {name!r}; known: {', '.join(BUILDS)}")
            return 2
        fname, fn = BUILDS[name]
        path = os.path.join(OUT, fname)
        save_slope_data_to_xlsx(fn(), path)
        back = load_slope_data(path)
        rep = preflight(back, "fem")
        errs = [f for f in rep.findings if f.severity == "error"]
        warns = [f for f in rep.findings if f.severity == "warning"]
        print(f"\n{fname}")
        print(f"  joint lines {len(back['joint_lines'])}, "
              f"joint regions {len(back.get('joint_zones') or [])}, "
              f"materials {len(back['materials'])}")
        for f in errs:
            print(f"  ERROR   {f.rule_id}: {f.message}")
        for f in warns:
            print(f"  warning {f.rule_id}: {f.message}")
        bad += len(errs)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.path.insert(0, REPO)
    sys.exit(main())
