"""Build the finite element companions for the docs FEM samples that no
benchmark builder covers.

The Griffiths & Lane verification cases are regenerated by
``benchmarks/make_griffiths_figures.py`` and the Rocscience rows by
``benchmarks/rocscience/make_rs2_figures.py``. Several docs models are covered by
neither: they were solved once in Studio and their companions saved from that
session, so nothing could rebuild them and nothing kept them honest. The pile
sample was worse off still — it shipped a mesh and no solution at all, so
documenting it meant solving a gravity trial on the spot and reporting a model
that had reached no failure.

What a solved finite element model carries, written for each:

    {stem}_mesh.json                the mesh the fields were solved on
    {stem}_fem_nodes.csv            the converged field
    {stem}_fem_elements.csv
    {stem}_fem_meta.json            the run record — bracket, tolerance,
                                    criterion, final interval, per-trial verdicts
    {stem}_fem_failure_*.csv/json   the at-failure mechanism
    {stem}_fem_reinf.csv (+failure) the per-bar forces, where the model has bars
    {stem}_fem_piles.csv (+failure) the per-pile-element forces, where it has piles

The mesh is the one the run's specification names — the page's tag where the
model is still written up, ``RETIRED`` where the write-up has gone — so the
sidecar and that specification describe one run. Two of the three had drifted off
it: the non-circular sample's saved companions were a 6,649-node mesh reading
FS = 1.684 while its page and its tag both say 1.53, and the reinforced slope
shipped a field with no factor of safety and no bar forces at all.

``griffiths1_load`` is on no page and carries no tag. It is solved on its OWN
committed mesh companion — the mesh its shipped fields were produced on, which is
an INPUT to this script and not one of its outputs — at the bracket and tolerance
declared below.

Deterministic: same mesh, same bracket, same trials. Re-running reproduces every
file it writes. Solves run on the pure-NumPy reference kernel, the path the locks
are defined on.

    PYTHONPATH=. python3 tools/make_fem_docs_sidecars.py               # every model
    PYTHONPATH=. python3 tools/make_fem_docs_sidecars.py noncircular   # one
    PYTHONPATH=. python3 tools/make_fem_docs_sidecars.py --meshes-only # mesh only

A model whose materials read a shipped seepage field is solved on the mesh
committed beside it rather than on a rebuilt one; see ``COMMITTED_MESH``.
"""
import contextlib
import io
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import run_tests as RT                                                  # noqa: E402
from xslope.fileio import load_slope_data                               # noqa: E402
from xslope.fem import (build_fem_data, export_fem_solution,            # noqa: E402
                        solve_ssrm, ssrm_run_record)
import xslope.fem as _fem                                               # noqa: E402
from xslope.mesh import (build_mesh_from_polygons, export_mesh_to_json,  # noqa: E402
                         extract_constraint_line_geometry,
                         extract_point_constraints, extract_size_regions,
                         get_material_polygons)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAMPLES_MD = os.path.join(REPO_ROOT, "docs", "fem", "samples.md")

#: The models solved from a specification rather than from a saved session: for
#: the ones still written up on the page, its own ``fem_ssrm`` tag is the single
#: source of truth for element type, mesh size, bracket and tolerance, and for
#: the factor of safety the run has to land on; for the rest, ``RETIRED`` below
#: carries the same specification.
TAGGED = {
    "noncircular": "xslope_noncircular_fem.xlsx",
    "reinforce": "xslope_reinforce_fem.xlsx",
    "piles": "xslope_piles_fem.xlsx",
    # The pile sample's unstabilized twin — the same model with its two pile rows
    # cleared, run as the before of a before and after, so it is a committed model
    # with a solved run of its own rather than a picture of a model nobody could
    # rebuild.
    "piles_nopile": "xslope_piles_fem_nopile.xlsx",
}

#: Models whose sample section is gone from the page but whose companions are
#: still fixtures. The reinforced slope and the two pile models were written up
#: on ``docs/fem/samples.md`` until the tutorials FEM-2 and FEM-3 built and ran
#: the same models step by step; the sections went, the workbooks stayed —
#: ``ROUNDTRIP_FILES``, the FEM preflight bases, ``report_check``,
#: ``fem_1d_details_check`` and ``nr_ssrm_check`` all open them by path — and so
#: their companions still have to be rebuildable. What the retired tags specified
#: is kept here in the same shape a parsed tag has, so ``build_tagged`` reads one
#: or the other and solves the same run either way. These are no longer
#: regression locks: FEM-2 and FEM-3 lock the same models at their own brackets,
#: and the factors of safety below are what these brackets produced.
RETIRED = {
    "reinforce": {"expected_fs": 1.534, "element_type": "tri6", "target_size": 2.0,
                  "tolerance": 0.01, "f_min": 1.1, "f_max": 1.9, "max_iter": 16000},
    "piles": {"expected_fs": 1.370, "element_type": "tri6", "target_size": 2.0,
              "tolerance": 0.01, "f_min": 1.0, "f_max": 1.6, "max_iter": 16000},
    "piles_nopile": {"expected_fs": 1.136, "element_type": "tri6", "target_size": 2.0,
                     "tolerance": 0.01, "f_min": 1.0, "f_max": 1.6, "max_iter": 16000},
}

#: The untagged model and the search it is solved by. Solved on the mesh
#: committed beside it rather than on a rebuilt one, so its shipped fields and
#: its new at-failure snapshot are the same discretization.
#:
#: Driven to a tolerance of 0.005 rather than the 0.01 the tagged rows use, for
#: the reason make_griffiths_figures gives for its own untagged stations: at 0.01
#: the bisection stops with the bracket still 0.009 wide, and which side of that
#: cell the reported midpoint falls on is a property of where the starting
#: bracket happened to land rather than of the model. A tagged row does not have
#: that problem, because its tag pins the bracket alongside the tolerance; this
#: one has no such record, so it is solved tightly enough that the bracket cannot
#: move the answer. The run saved from Studio reported 1.3453 — the neighbouring
#: cell of the coarser search, from a session whose bracket is not on record.
UNTAGGED = {
    "griffiths1_load": {
        "xlsx": os.path.join(REPO_ROOT, "docs", "fem", "files",
                             "xslope_griffiths1_load.xlsx"),
        "options": {"F_min": 1.2, "F_max": 1.5, "tolerance": 0.005},
        "max_iterations": 16000,
    },
}

#: Tagged models that must be solved on the mesh COMMITTED beside them rather than
#: on a rebuilt one. Their materials read pore pressures off a shipped seepage
#: field, and that field is nodal: any other discretization is a different model,
#: and build_fem_data would silently zero the pore pressures. The page's tag is
#: still the whole specification — bracket, tolerance, iteration cap, and the
#: factor of safety the run has to land on — and ``run_tests.build_fem_ssrm_case``
#: is the single implementation of tag -> (mesh, fem_data, options), so this route
#: solves exactly what the lock solves.
#:
#: The Johnson Reservoir dam of docs/seep/seep_slope.md is here because its
#: companions were saved from a Studio session in July 2026 and then went stale:
#: they read FS = 1.691 at F = 1.6875, outside the bracket its tag names, while the
#: page and the tag both say 1.25. The mesh was not the problem — those fields sat
#: on the same 3,362-node companion this route solves on — so what had drifted was
#: the run, not the discretization. Studio attaches the companions the moment the
#: workbook opens, so the stale answer was the first thing a reader saw.
COMMITTED_MESH = {
    "johnson_res": (os.path.join(REPO_ROOT, "docs", "seep", "seep_slope.md"),
                    os.path.join(REPO_ROOT, "docs", "seep", "files",
                                 "xslope_johnson_res.xlsx")),
}

#: Models whose FEM solution sidecars belong to another builder, and which need
#: only the mesh companion that builder does not write. Rebuilt from the row's own
#: tag; the node count is checked against the committed field CSV, so a mesh that
#: is not the one the fields were solved on is refused rather than written.
MESH_ONLY = {
    "acads_simple": ("rs2.md", "RS2-1"),
    "acads_weak_layer": ("rs2.md", "RS2-5"),
    "arai_tagyo": ("rs2.md", "RS2-10"),
}


def _quiet(fn, *a, **k):
    with contextlib.redirect_stdout(io.StringIO()):
        return fn(*a, **k)


def _tag(md_path, match):
    """The one ``fem_ssrm`` tag on ``md_path`` that ``match`` selects."""
    hits = [t for t in RT.parse_test_tags(md_path)
            if t.get("type") == "fem_ssrm" and match(t)]
    if len(hits) != 1:
        raise RuntimeError(f"{os.path.basename(md_path)}: {len(hits)} fem_ssrm "
                           f"tags match, expected exactly one")
    return hits[0]


def _mesh_for(tag, path):
    """The mesh a tag names, and the model it belongs to."""
    slope_data = load_slope_data(path)
    lines, _n_reinf, _n_pile = extract_constraint_line_geometry(slope_data)
    polys = get_material_polygons(slope_data, reinf_lines=lines)
    mesh = _quiet(build_mesh_from_polygons, polys,
                  target_size=tag.get("target_size"),
                  element_type=tag["element_type"], lines=lines,
                  element_size_1d=slope_data.get("element_size_1d"),
                  point_constraints=extract_point_constraints(slope_data),
                  size_regions=extract_size_regions(slope_data),
                  **RT._refine_kwargs(tag))
    return slope_data, mesh


def _solve(fem_data, options, max_iterations):
    with RT._force_fast_kernel(_fem, False):
        return _quiet(solve_ssrm, fem_data, debug_level=0,
                      capture_failure_state=True,
                      max_iterations=max_iterations, **options)


def _write(fem_data, result, stem, mesh, extra):
    """The fields, the mesh and the run record, for one solved model."""
    field = result["last_solution"]
    meta = ssrm_run_record(result, fem_data, extra["options"])
    meta.update(extra["meta"])
    # The strength reduction factor the WRITTEN FIELD was solved at — not the
    # factor of safety, and carried by neither CSV. Studio's writer records it.
    meta["F"] = field.get("F")
    _quiet(export_fem_solution, fem_data, field, stem, meta=meta,
           failure_solution=result.get("failure_solution"))
    export_mesh_to_json(mesh, f"{stem}_mesh.json")


def build_tagged(name):
    xlsx = TAGGED[name]
    path = os.path.join(REPO_ROOT, "docs", "fem", "files", xlsx)
    tag = RETIRED.get(name) or _tag(
        SAMPLES_MD, lambda t: os.path.basename(t["file"]) == xlsx)
    t0 = time.time()
    slope_data, mesh = _mesh_for(tag, path)
    fem_data = _quiet(build_fem_data, slope_data, mesh)
    options = {"F_min": tag["f_min"], "F_max": tag["f_max"],
               "tolerance": tag["tolerance"]}
    result = _solve(fem_data, options, int(tag["max_iter"]))
    if not result.get("converged"):
        raise RuntimeError(f"{name}: SSRM did not converge")
    fs = result["FS"]
    expected = float(tag["expected_fs"])
    # The tag is the truth, judged the way the suite judges it: the run has to
    # land inside the tag's own tolerance of the locked answer. A run that does
    # not is reported, not written — a sidecar that disagrees with the lock
    # beside it is the defect this script exists to remove.
    if abs(fs - expected) > float(tag["tolerance"]):
        raise RuntimeError(
            f"{name}: solved FS = {fs:.6f}, tag expects {expected:.3f} "
            f"+/- {float(tag['tolerance']):g} — nothing written")
    stem = os.path.splitext(path)[0]
    _write(fem_data, result, stem, mesh, {
        "options": options,
        "meta": {"analysis_type": "ssrm", "FS": fs,
                 "element_type": tag["element_type"],
                 "target_size": tag.get("target_size"),
                 "max_iter": int(tag["max_iter"]),
                 "expected_fs": expected},
    })
    print(f"{name}: FS = {fs:.4f} (tag {expected:.3f}), "
          f"{len(mesh['nodes'])} nodes, {len(mesh['elements'])} elements, "
          f"{len(result['trials'])} trials, {time.time() - t0:.0f}s")


def build_untagged(name):
    spec = UNTAGGED[name]
    path = spec["xlsx"]
    t0 = time.time()
    slope_data = load_slope_data(path)
    mesh = slope_data.get("mesh")
    if mesh is None:
        raise RuntimeError(f"{name}: no committed mesh companion to solve on")
    fem_data = _quiet(build_fem_data, slope_data, mesh)
    result = _solve(fem_data, spec["options"], spec["max_iterations"])
    if not result.get("converged"):
        raise RuntimeError(f"{name}: SSRM did not converge")
    stem = os.path.splitext(path)[0]
    _write(fem_data, result, stem, mesh, {
        "options": spec["options"],
        "meta": {"analysis_type": "ssrm", "FS": result["FS"],
                 "max_iter": spec["max_iterations"]},
    })
    print(f"{name}: FS = {result['FS']:.4f}, {len(mesh['nodes'])} nodes, "
          f"{len(mesh['elements'])} elements, {len(result['trials'])} trials, "
          f"{time.time() - t0:.0f}s")


def build_committed_mesh(name):
    """A tagged model solved on its own committed mesh (see ``COMMITTED_MESH``).

    Writes the converged field and the run record only — no mesh (the mesh is an
    input here, not an output) and no at-failure snapshot, which is the file set
    these models ship."""
    md, path = COMMITTED_MESH[name]
    tag = _tag(md, lambda t: t["file"] == path)
    t0 = time.time()
    fem_data, kwargs, f_min, f_max, tolerance = RT.build_fem_ssrm_case(tag)
    options = {"F_min": f_min, "F_max": f_max, "tolerance": tolerance}
    with RT._force_fast_kernel(_fem, False):
        result = _quiet(solve_ssrm, fem_data, debug_level=0, **options, **kwargs)
    if not result.get("converged"):
        raise RuntimeError(f"{name}: SSRM did not converge")
    fs = result["FS"]
    expected = float(tag["expected_fs"])
    if abs(fs - expected) > float(tag["tolerance"]):
        raise RuntimeError(
            f"{name}: solved FS = {fs:.6f}, tag expects {expected:.3f} "
            f"+/- {float(tag['tolerance']):g} — nothing written")
    field = result["last_solution"]
    meta = ssrm_run_record(result, fem_data, options)
    meta.update({"FS": fs, "analysis": "ssrm", "F": field.get("F"),
                 "expected_fs": expected})
    stem = os.path.splitext(path)[0]
    _quiet(export_fem_solution, fem_data, field, stem, meta=meta)
    print(f"{name}: FS = {fs:.4f} (tag {expected:.3f}), "
          f"{len(fem_data['nodes'])} nodes, {len(result['trials'])} trials, "
          f"{time.time() - t0:.0f}s")


def build_mesh_only(name):
    page, bench = MESH_ONLY[name]
    md = os.path.join(REPO_ROOT, "docs", "verification", page)
    tag = _tag(md, lambda t: t.get("benchmark") == bench)
    path = os.path.join(REPO_ROOT, "docs", "lem", "files", f"xslope_{name}.xlsx")
    _slope_data, mesh = _mesh_for(tag, path)
    stem = os.path.splitext(path)[0]
    # The committed field CSV counts the nodes the solution was found on. A
    # rebuilt mesh that does not match it is a different discretization, and
    # writing it would put a mesh beside fields it never carried.
    import pandas as pd
    nodes_csv = f"{stem}_fem_nodes.csv"
    if os.path.exists(nodes_csv):
        n_solved = len(pd.read_csv(nodes_csv, comment="#"))
        if n_solved != len(mesh["nodes"]):
            raise RuntimeError(
                f"{name}: the {bench} tag meshes to {len(mesh['nodes'])} nodes "
                f"and the committed field carries {n_solved} — nothing written")
    export_mesh_to_json(mesh, f"{stem}_mesh.json")
    print(f"{name}: {len(mesh['nodes'])} nodes, {len(mesh['elements'])} "
          f"elements ({bench})")


def main(argv):
    wanted = [a for a in argv if not a.startswith("-")]
    meshes_only = "--meshes-only" in argv
    for name in MESH_ONLY:
        if not wanted or name in wanted:
            build_mesh_only(name)
    if meshes_only:
        return 0
    for name in TAGGED:
        if not wanted or name in wanted:
            build_tagged(name)
    for name in COMMITTED_MESH:
        if not wanted or name in wanted:
            build_committed_mesh(name)
    for name in UNTAGGED:
        if not wanted or name in wanted:
            build_untagged(name)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
